### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KnowNothingCoder** [Soumya-0x000/Movix#6]
Open your browser and navigate to http://localhost:3000 to view the app.

As per your instructions I'm unable to open the apk

**Comment by Soumya-0x000** [comment]
Actually u have to first clone this repo in your machine using `git clone https://github.com/Soumya-0x000/Movix`. Then u have to put 'npm run dev' or 'yarn run dev' into your vs code terminal from the same directory where u have cloned the repo. Then u can see this web app running in your localhost port 3000.

**Comment by Soumya-0x000** [comment]
> Open your browser and navigate to [http://localhost:3000 to](http://localhost:3000%C2%A0to) view the app.
> 
> As per your instructions I'm unable to open the apk
